// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestia/lst/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the lst module's genesis state.
type GenesisState struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// baskets is the list of all baskets
	Baskets []Basket `protobuf:"bytes,2,rep,name=baskets,proto3" json:"baskets"`
	// pending_redemptions is the list of all pending redemptions
	PendingRedemptions []PendingRedemption `protobuf:"bytes,3,rep,name=pending_redemptions,json=pendingRedemptions,proto3" json:"pending_redemptions"`
	// next_basket_id is the next ID to be assigned to a new basket
	NextBasketId uint64 `protobuf:"varint,4,opt,name=next_basket_id,json=nextBasketId,proto3" json:"next_basket_id,omitempty"`
	// next_pending_id is the next ID to be assigned to a pending redemption
	NextPendingId uint64 `protobuf:"varint,5,opt,name=next_pending_id,json=nextPendingId,proto3" json:"next_pending_id,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f28cabd17a3af4ed, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetBaskets() []Basket {
	if m != nil {
		return m.Baskets
	}
	return nil
}

func (m *GenesisState) GetPendingRedemptions() []PendingRedemption {
	if m != nil {
		return m.PendingRedemptions
	}
	return nil
}

func (m *GenesisState) GetNextBasketId() uint64 {
	if m != nil {
		return m.NextBasketId
	}
	return 0
}

func (m *GenesisState) GetNextPendingId() uint64 {
	if m != nil {
		return m.NextPendingId
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "celestia.lst.v1.GenesisState")
}

func init() { proto.RegisterFile("celestia/lst/v1/genesis.proto", fileDescriptor_f28cabd17a3af4ed) }

var fileDescriptor_f28cabd17a3af4ed = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4e, 0x32, 0x31,
	0x14, 0x85, 0xa7, 0xc0, 0xcf, 0x9f, 0x54, 0x94, 0xa4, 0x9a, 0x38, 0x21, 0x5a, 0x09, 0x31, 0x86,
	0x8d, 0x6d, 0xd0, 0x18, 0xf7, 0x6c, 0x0c, 0x3b, 0x83, 0x2b, 0xdd, 0x90, 0x42, 0x9b, 0xda, 0x08,
	0xd3, 0x66, 0x5a, 0x09, 0xbe, 0x85, 0x6f, 0xe1, 0xab, 0xb0, 0x64, 0xe9, 0xca, 0x18, 0x78, 0x11,
	0x43, 0xdb, 0x61, 0x01, 0xba, 0xbb, 0xb9, 0xdf, 0xb9, 0xe7, 0x9c, 0x5c, 0x78, 0x3a, 0x12, 0x63,
	0x61, 0x9d, 0x62, 0x74, 0x6c, 0x1d, 0x9d, 0x76, 0xa8, 0x14, 0x99, 0xb0, 0xca, 0x12, 0x93, 0x6b,
	0xa7, 0x51, 0xbd, 0xc0, 0x64, 0x6c, 0x1d, 0x99, 0x76, 0x1a, 0x47, 0x52, 0x4b, 0xed, 0x19, 0x5d,
	0x4f, 0x41, 0xd6, 0x38, 0xd9, 0x76, 0x31, 0x2c, 0x67, 0x13, 0xfb, 0x17, 0x1d, 0x32, 0xfb, 0x22,
	0x5c, 0xa4, 0x3b, 0x0d, 0x8c, 0xc8, 0xb8, 0xca, 0x64, 0xc0, 0xad, 0x8f, 0x12, 0xac, 0xdd, 0x85,
	0x4e, 0x0f, 0x8e, 0x39, 0x81, 0x6e, 0x60, 0x35, 0xb8, 0xa7, 0xa0, 0x09, 0xda, 0x7b, 0x57, 0xc7,
	0x64, 0xab, 0x23, 0xb9, 0xf7, 0xb8, 0x5b, 0x99, 0x7f, 0x9d, 0x25, 0xfd, 0x28, 0x46, 0xb7, 0xf0,
	0x7f, 0x88, 0xb5, 0x69, 0xa9, 0x59, 0xfe, 0xf5, 0xae, 0xeb, 0x79, 0xbc, 0x2b, 0xd4, 0xe8, 0x11,
	0x1e, 0xc6, 0x46, 0x83, 0x5c, 0x70, 0x31, 0x31, 0x4e, 0xe9, 0xcc, 0xa6, 0x65, 0x6f, 0xd2, 0xda,
	0x0d, 0x0f, 0xda, 0xfe, 0x46, 0x1a, 0xfd, 0x90, 0xd9, 0x06, 0x16, 0x9d, 0xc3, 0x83, 0x4c, 0xcc,
	0xdc, 0x20, 0x44, 0x0d, 0x14, 0x4f, 0x2b, 0x4d, 0xd0, 0xae, 0xf4, 0x6b, 0xeb, 0x6d, 0x68, 0xd3,
	0xe3, 0xe8, 0x02, 0xd6, 0xbd, 0xaa, 0x68, 0xa1, 0x78, 0xfa, 0xcf, 0xcb, 0xf6, 0xd7, 0xeb, 0x98,
	0xd7, 0xe3, 0xdd, 0xde, 0x7c, 0x89, 0xc1, 0x62, 0x89, 0xc1, 0xf7, 0x12, 0x83, 0xf7, 0x15, 0x4e,
	0x16, 0x2b, 0x9c, 0x7c, 0xae, 0x70, 0xf2, 0x44, 0xa5, 0x72, 0xcf, 0xaf, 0x43, 0x32, 0xd2, 0x13,
	0x5a, 0xf4, 0xd5, 0xb9, 0xdc, 0xcc, 0x97, 0xcc, 0x18, 0x3a, 0xf3, 0xff, 0x77, 0x6f, 0x46, 0xd8,
	0x61, 0xd5, 0xff, 0xfe, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x68, 0x97, 0x9a, 0x1e, 0x02,
	0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextPendingId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextPendingId))
		i--
		dAtA[i] = 0x28
	}
	if m.NextBasketId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextBasketId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.PendingRedemptions) > 0 {
		for iNdEx := len(m.PendingRedemptions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingRedemptions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Baskets) > 0 {
		for iNdEx := len(m.Baskets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Baskets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Baskets) > 0 {
		for _, e := range m.Baskets {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingRedemptions) > 0 {
		for _, e := range m.PendingRedemptions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextBasketId != 0 {
		n += 1 + sovGenesis(uint64(m.NextBasketId))
	}
	if m.NextPendingId != 0 {
		n += 1 + sovGenesis(uint64(m.NextPendingId))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Baskets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Baskets = append(m.Baskets, Basket{})
			if err := m.Baskets[len(m.Baskets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingRedemptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingRedemptions = append(m.PendingRedemptions, PendingRedemption{})
			if err := m.PendingRedemptions[len(m.PendingRedemptions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextBasketId", wireType)
			}
			m.NextBasketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextBasketId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextPendingId", wireType)
			}
			m.NextPendingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextPendingId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
